### ISSUE TITLE
Converting model using model.generate() gives meaningless output

### ISSUE THREAD

**Issue by yunqili0809** [astramind-ai/Mixture-of-depths#14]
I coverted llama-2-7b-hf and trying to run the generate() function to inference inputs, but the model output is giving the meanless response, could you help me with this issue?

![code](https://github.com/user-attachments/assets/ad8ac39f-3366-4e9e-8c9c-4143986af305)

![meaningless](https://github.com/user-attachments/assets/c8d216e2-dd93-4645-91a0-f146139e1f8a)

**Comment by yunqili0809** [comment]
the top part of the output was saying that when transformers update to 4.50 and 4.48, those will produce an error, I'm currently using transformers 4.46

**Comment by yunqili0809** [comment]
Hi @mlinmg, I haven't figured out what caused this issue, could you help me with it?

**Comment by mlinmg** [comment]
You have to finetune a model in order to use the router, it does not work out of the box. You shall finetune the converted model and then try to inference it.
