### ISSUE TITLE
Misaligned implementation with paper

### ISSUE THREAD

**Issue by starsholic** [astramind-ai/Mixture-of-depths#5]
Hi! Here in paper 3.4 eq1, 
![1714224387010](https://github.com/astramind-ai/Mixture-of-depths/assets/52476332/6498c533-796e-4239-86ad-7dc3e640a3ea)

should be 
`output = processed_tokens + x`
I wonder why only add selected tokens here
https://github.com/astramind-ai/Mixture-of-depths/blob/103aa4b6c211346599cc8b853cc3108bf9cb72d0/MoD/MoD.py#L93

**Comment by Aafiya-H** [comment]
Hello,
Thank you so much for pointing this out. I agree with the issue and the solution you mentioned. Have you proceeded with this solution because I think the implementation still has this issue?
